### ISSUE TITLE
addClass

### ISSUE THREAD

**Issue by pierrenel** [antoniobrandao/ab-lightbox#2]
Hi, does your library assume you have jQuery installed, but it's not marked as a dependency? 

Maybe it should use 

`lightbox_base_element.classList.add('ui-lightbox-image')`

instead of 

`lightbox_base_element.addClass('ui-lightbox-image')`

?

**Comment by antoniobrandao** [comment]
Hey thanks for the warning. It was missing a dependency indeed (ab-element) for the addClass method. But I used your suggestion, now it has no dependency at all. Check it out on version 1.2.4. Thanks again!
